version: '3'
services:
  elasticsearch:
    image: elasticsearch:8.12.1
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=changeme # user default: elastic
      - xpack.security.enabled=true
      - xpack.security.authc.api_key.enabled=true
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - elastic

  kibana:
    image: kibana:8.12.1
    environment:
      KIBANA_FLEET_SETUP: 1
      KIBANA_FLEET_HOST: http://kibana:5601
      KIBANA_FLEET_USERNAME: elastic
      KIBANA_FLEET_PASSWORD: changeme
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
      ELASTICSEARCH_SERVICEACCOUNTTOKEN: AAEAAWVsYXN0aWMva2liYW5hL3Rva2VuMTpBSUNfTUN3UFNQZXFfd094Ti1ZcmlR
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    volumes:
      - kibana-data:/usr/share/kibana/data
    networks:
      - elastic
  
  fleet-server:
    image: elastic/elastic-agent:8.12.1
    container_name: fleet-server
    environment:
      FLEET_SERVER_ENABLE: 1
      FLEET_SERVER_ELASTICSEARCH_HOST: http://elasticsearch:9200
      # FLEET_SERVER_ELASTICSEARCH_CA
      FLEET_SERVER_SERVICE_TOKEN: i5gTq02PT4Wb6BF5C6ub8Q
    depends_on:
      - elasticsearch
      - kibana
    ports:
      - "8220:8220"
    networks:
      - elastic
  
  elastic-agent:
    image: elastic/elastic-agent:8.12.1
    container_name: elastic-agent
    environment:
      FLEET_ENROLL: 1
      FLEET_URL: http://fleet-server:8220
    depends_on:
      - elasticsearch
      - kibana
      - fleet-server
    ports:
      - "5044:5044"
    networks:
      - elastic

volumes:
  elasticsearch-data:
  kibana-data:

networks:
  elastic:
    driver: bridge
