pipeline {
    agent any
    tools{
        nodejs '18.18.0'
    }
    stages {
        stage('Clone') {
            steps{
                git 'https://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@github.com/gberdejo/project-base-1.git'
            }
        }

        stage('build') {
            steps{
                sh 'node --version'
                sh 'npm install'
            }
        }
    }
}