pipeline {
    agent any
    tools{
        nodejs '18.18.0'
        docker '1.5'
    }
    stages {
        stage('Clone') {
            steps{
                git 'https://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@github.com/gberdejo/project-base-1.git'
            }
        }

        stage('Install dependencies') {
            steps{
                sh 'node --version'
                sh 'npm install'
            }
        }

        stage('Test') {
            steps{
                sh 'npm run lint'
            }
        }

        stage('Build') {
            steps {
                sh 'npm run build'
            }
        }

        stage('Build Imagen Docker') {
            steps {
                script {
                    dockerImage = docker.build('gberdejo/project-base-1:lasted', '.')
                }
            }
        }
    }
}