version: '3'
services:
  rabbitmq-dev:
    image: bitnami/rabbitmq
    container_name: rabbitmq-dev
    environment:
      - RABBITMQ_USERNAME=user
      - RABBITMQ_PASSWORD=bitnami
    ports:
      - "5682:5672"
      - "15682:15672"
    volumes:
      - rabbitmq-data:/bitnami/rabbitmq
    networks:
      transformacion-digital:
        ipv4_address: 172.21.0.2

  database-dev:
    image: mysql:5.7
    container_name: database-dev
    volumes: 
      - database-data:/var/lib/mysql
    ports:
      - "3307:3306"
    command: mysqld --sql_mode=""
    environment:
      MYSQL_DATABASE: middleware
      MYSQL_ROOT_PASSWORD: 123456
      TZ: America/Lima
    networks:
      transformacion-digital:
        ipv4_address: 172.21.0.3

  mongo-dev:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongo-dev
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes: 
      - mongo-data:/data/db
    networks:
      transformacion-digital:
        ipv4_address: 172.21.0.4
  
  redis-dev:
      image: redis:6.2-alpine
      container_name: redis-dev
      ports:
        - 6379:6379
      command: redis-server --save 20 1 --loglevel warning
      environment:
        - ALLOW_EMPTY_PASSWORD=yes
      networks:
        transformacion-digital:
              ipv4_address: 172.21.0.5

volumes:
  rabbitmq-data:
  database-data:
  mongo-data:

networks:
  transformacion-digital:
    name: transformacion-digital-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/24
          gateway: 172.21.0.1

