version: '3'
services:
  jenkins_v1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins_v1
    ports:
      - "8080:8080"  # Puerto para la interfaz web de Jenkins
      - "50000:50000"  # Puerto para la comunicación de agentes
    volumes:
      - jenkins-data:/var/jenkins_home
    networks:
      - jenkins-net

networks:
  jenkins-net:

volumes:
  jenkins-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/