# Utilizamos la imagen base de Jenkins LTS
FROM jenkins/jenkins:lts

# Cambiamos al usuario root para poder instalar herramientas adicionales
USER root

# Instalamos herramientas adicionales si es necesario
# RUN apt-get update && apt-get install -y <nombre_de_herramienta>

# Cambiamos de nuevo al usuario jenkins
USER jenkins
