pipeline {
    agent any

    tools { go '1.21.1' }

    environment {
        GO111MODULE='on'
    }

    stages {
        stage('Test') {
            steps {
                git 'https://github.con/AdminTurnedDevOps/go-webapp-sample.git'
                sh 'go test ./...'
            }
        }
        stage('Build'){
            steps{
                sh 'go build .'
            }
        }
        stage('Run'){
            steps{
                sh 'cd /var/lib/jenkins/workspace/pipe-go && go-webapp-sample &'
            }
        }
    }
}